### ISSUE TITLE
First-Class support for `@stream`/`@defer` in strawberry

### ISSUE THREAD

**Issue by erikwrede** [strawberry-graphql/strawberry#2914]
## First-Class support for `@stream`/`@defer` in strawberry
This issue is going to collect all necessary steps for an awesome stream and defer devX in Strawberry 🍓 

First steps collected today together in discovery session with @patrick91 @bellini666 

#### ToDos for an initial support:

- [ ] Add support for `[async/sync]` generators in return types
- [ ] Make sure `GraphQLDeferDirective`, `GraphQLStreamDirective`, are in the GQL-Core schema
  Flag in Schema(query=Query, config={enable_stream_defer: False}) - default true
- [ ] Add incremental delivery support to all the views
- [ ] FastAPI integration -> Maybe in the Async Base View?
- [ ] Explore Sync View Integration

### long term goals
_incomplete list of problems / design improvement potential of the current raw implementation_

#### Possible solutions
- custom query execution plan engine
- Add @streamable directive to schema fields automatically if field is streamable, including custom validation rule

Some playground code: https://gist.github.com/erikwrede/993e1fc174ee75b11c491210e4a9136b

**Comment by owen-zora** [comment]
Hey @erikwrede what's the latest updates for this?

**Comment by patrick91** [comment]
@owen-zora this will probably be blocked on GraphQL core (unless we are ok with people using the alpha release) 

and this PR #3076 which has some building blocks for adding support for incremental delivery

**Comment by owen-zora** [comment]
Got it, thanks! Will we be able to merge this PR as soon as the GraphQL core is unblocked?

**Comment by patrick91** [comment]
> Got it, thanks! Will we be able to merge this PR as soon as the GraphQL core is unblocked?

Not sure, when I tried implementing it was quite a bit of work (because we need to adapt our integrations and our execution code to support incremental responses)

Do you have a use case for this? ☺️

**Comment by owen-zora** [comment]
@patrick91 , yes! We are doing a lazy backfill for video processing. E.g. when a user requests a video in a graphql field, if we haven't processed this video yet, we will need to trigger a job to process the video then give the response back to the client. Without @defer, it might take up to 20 seconds to give all response back to the client. We are currently only able to run periodical polling. The @defer will help us a lot!

**Comment by patrick91** [comment]
@owen-zora thanks for the context, I'll see if I can merge the PR for adding http subscriptions (which I'm pretty sure will help with incremental delivery too)

Not sure when we can get to this issue next (unless you want to sponsor some dedicated time), I'm trying to work on older issues at the moment, since I've been pretty busy on other stuff :D

**Comment by owen-zora** [comment]
Got it, how can I sponsor some time for this?

**Comment by simkessy** [comment]
Any updates on this?

**Comment by thearchitector** [comment]
Is there an update on support for this feature? Support for Apollo's multipart subscriptions is great but somewhat limited in the realm of IDEs, whereas `@stream` and `@defer` seem to be pretty widely adopted.

**Comment by patrick91** [comment]
@thearchitector yes! see this pr #3819
