### ISSUE TITLE
Documentation meta issue

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#328]
## General

- [x] Getting started (https://strawberry.rocks/docs/)
- [x] Schema Basic (https://strawberry.rocks/docs/schema-basics)
- [x] Query Basics @jaydenwindle (https://strawberry.rocks/docs/queries)
- [x] Mutation Basics (https://strawberry.rocks/docs/mutations)
- [x] Subscriptions Basics 
- [x] Why strawberry (code first, batteries included, dataclasses) #603 

## Types

- [ ] Fields (#450)
	- [x] Private fields (https://github.com/strawberry-graphql/strawberry/pull/479)
- [ ] Input types
- [x] Interfaces
- [x] Generics
- [x] Custom scalars
- [x] [Enums](https://github.com/strawberry-graphql/strawberry/blob/master/docs/02_types/enums.md)
- [x] Union
- [ ] Schema directives
- [ ] Resolvers

## Integrations @jaydenwindle 

- [x] Django support
- [x] Flask support
- [x] ASGI Support

## Features

- [x] Error handling
	- > 1. what happens when there's an exception in the code (and how to debug if we manage to improve things there)
	  > 2. validation errors, ie when sending bad queries/inputs
      > 3. expected errors vs unexpected errors
- [x] File uploads
- [ ] Authentication
- [x] Pagination
- [x] Permissions
- [x] Federation (experimental)
- [x] Extensions (https://strawberry.rocks/docs/feature/extensions)

## Operation

- [ ] Tracing / profiling (https://strawberry.rocks/docs/ops/tracing)
- [ ] Testing
- [ ] Deployment

## Demos

- [ ] SWAPI 
- [ ] Subscription
- [ ] More

---

## Examples of good documentation

* https://docs.djangoproject.com/en/3.1/
* https://graphql.org/learn/

## Useful resources

* https://developers.google.com/tech-writing
* https://www.writethedocs.org/
* https://documentation.divio.com/

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/328">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/328/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/328/pledge.svg">
</picture>
</a>

**Comment by skilkis** [comment]
@patrick91 based on your reply in the Discord, I think resolver arguments could also be added to this list. The following is quite handy to know:

```python
def resolver(python_name_argument: Annotated[str, strawberry.argument(name="graphqlName")]): ...
```

**Comment by skilkis** [comment]
Based on https://github.com/strawberry-graphql/strawberry/issues/1879#issuecomment-1170889434 `LazyType` should be added to the list above as a way to deal with circular dependencies 😊
