### ISSUE TITLE
Deprecate starlite

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#3359]
Now that we Litestar support I think we can deprecate Starlite 😊

```[tasklist]
### Tasks
- [ ] Add notice in the docs
- [ ] Use typing_extensions.deprecated to mark class as deprecated (see https://peps.python.org/pep-0702/)
- [ ] Trigger deprecation warning (with test), this might 
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3359">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3359/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3359/pledge.svg">
</picture>
</a>

**Comment by erikwrede** [comment]
@Birdi7 Please feel free to go ahead with this 😊 If you need assistance or a review, feel free to ping me
